### ISSUE TITLE
Number of countries and members listed under the Members tab

### ISSUE THREAD

**Issue by ghost** [level73/membernet#210] opened 2020-06-02 12:26 UTC
How are the number of countries 78 and the number of members - 254 - formulated?

**Comment by IronRunes** [comment] 2020-06-03 05:58
Number of members: 
Looks at members are currently members, excludes donors, IFAD and all ILC units
Then looks at countries associated to those members

**Comment by decasadecasa** [comment] 2020-06-03 07:50
hi. the issue is that according to our data from other staff, we should have 75 countries- Krishna checked the members and it all looked ok- so we are wondering where this could be pulling from. @kravinthiren did you also check donors/past members? @IronRunes do past members contribute to this count?

**Comment by ghost** [comment] 2020-06-03 08:02
﻿Didn’t check past members and donors.
I believe donors are excluded and only current members are counted.

“Looks at members are currently members, excludes donors, IFAD and all ILC units

Then looks at countries associated to those members”

Thanks,

Krishna Ravinthiren

On Jun 3, 2020, at 09:50, decasadecasa <notifications@github.com> wrote:

﻿

hi. the issue is that according to our data from other staff, we should have 75 countries- Krishna checked the members and it all looked ok- so we are wondering where this could be pulling from. @kravinthiren<https://github.com/kravinthiren> did you also check donors/past members? @IronRunes<https://github.com/IronRunes> do past members contribute to this count?

**Comment by decasadecasa** [comment] 2020-06-03 14:48
@IronRunes - were we able to determine where this is coming from? the old members? please advise on how we can fix. Number should be 75

**Comment by IronRunes** [comment] 2020-06-18 14:21
this should be fixed, please check on DEV

**Comment by decasadecasa** [comment] 2020-06-18 14:25
still read 78 on DEV. should be 75.
![capture](https://user-images.githubusercontent.com/40179449/85032619-52b8e280-b180-11ea-83f9-01b74cd713f4.PNG)

**Comment by IronRunes** [comment] 2020-06-22 09:23
good catch. 
It is fixed on the login page though, right?

**Comment by IronRunes** [comment] 2020-06-22 09:53
should be fixed now

**Comment by ghost** [comment] 2020-06-25 14:01
It still shows 78 countries.

**Closed as completed** 2021-12-02 16:24 UTC
Labels: Type: Question, Status: Review Needed
