### ISSUE TITLE
NES/CBI Reports and Facility Reports not working

### ISSUE THREAD

**Issue by ghost** [level73/membernet#225] opened 2020-08-04 12:59 UTC
I tried adding the NES/CBI and Facility reports twice and the first time when I saved it the webpage went blank for both NES/CBI and Facility Reports, and the second time the error message below showed for Facility Reports and the fields were cleared where for NES/CBI Reports the webpage went blank again. 

SQLSTATE[01000]: Warning: 1265 Data truncated for column ‘d3_q1_n1’ at row 1
1:25
Couldn’t create the data record. There must be some issue with a specific field or data point. [551]

[NES CBI 2019 Final Report - Sarin rescued.docx](https://github.com/level73/membernet/files/5022208/NES.CBI.2019.Final.Report.-.Sarin.rescued.docx)
[SAPA Report 2020_Feb 20.docx](https://github.com/level73/membernet/files/5022209/SAPA.Report.2020_Feb.20.docx)
[Facility Report Form_WfW_final.docx](https://github.com/level73/membernet/files/5022210/Facility.Report.Form_WfW_final.docx)

**Comment by IronRunes** [comment] 2020-08-04 14:48
@kravinthiren looking at the forms you sent over, the problem is that numeric fields (such as the "# of alliances/parties") should only and exclusively hold numbers. no characters or symbols, only numbers. 
this is mandatory, as we need those numbers to compile aggregates and stats.

**Comment by ghost** [comment] 2020-08-04 14:55
Thanks Alan, yes I did only insert numbers in those fields.

Best regards,

Krishna Ravinthiren

On Aug 4, 2020, at 16:48, Alan Zard <notifications@github.com> wrote:

﻿

@kravinthiren<https://github.com/kravinthiren> looking at the forms you sent over, the problem is that numeric fields (such as the "# of alliances/parties") should only and exclusively hold numbers. no characters or symbols, only numbers.
this is mandatory, as we need those numbers to compile aggregates and stats.

**Comment by IronRunes** [comment] 2020-08-04 15:21
I just added the facility report you sent over. I had no issue with the data or saving it. 
That specific error shows up when data is not in the correct format for the database. please also check for unwanted or unnecessary whitespaces. 
All the best

**Comment by ghost** [comment] 2020-08-04 17:10
I realized the issue now, there are instances where for years that multiple years cannot be added for example I added the NES/CBI Reports for [NES Cambodia](https://membernet.landcoalition.org/manage/reporting/92) the issue is the year for 'Year the change took place’ for 2.1 it should be 2001 and 2019 but I cannot both so I went with the latest one - 2019. If you are able to add both that would be great otherwise I would ask @decasadecasa if we can go with the latest change which is 2019 and close the matter?

**Comment by decasadecasa** [comment] 2020-08-06 15:43
@kravinthiren - has the issue been resolved/identified? can we close the issue?

**Comment by ghost** [comment] 2020-08-06 16:27
I have completed the entry of the reports on MemberNet, however a key issue was the repeated reentering of the reports on MemberNet because they were not being saved and the screen goes blank, this resulted in a minimum redoing of the reports twice. Perhaps if can examine this further and resolve the issue it would be awesome.

Thank you,

Krishna Ravinthiren



On Aug 6, 2020, at 5:44 PM, decasadecasa <notifications@github.com<mailto:notifications@github.com>> wrote:



@kravinthiren<https://github.com/kravinthiren> - has the issue been resolved/identified? can we close the issue?

**Closed as completed** 2020-10-06 07:37 UTC
Labels: Platform: Membernet
